# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the input remotectl drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_RK_REMOTECTL_GPIO)     += rkxx_remotectl.o
obj-$(CONFIG_ROCKCHIP_REMOTECTL_PWM)	+= rockchip_pwm_remotectl.o
